hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("waybar")
    hl.exec_cmd("wl-paste --type text --watch cliphist store #Stores only text data")
    hl.exec_cmd("wl-paste --type image --watch cliphist store #Stores only image data")
    hl.exec_cmd("swaync")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("bash ~/dotfiles/Scripts/vitwifi.sh")
    hl.exec_cmd("nm-applet")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("touch ~/.config/hypr/confs/gitignored.conf")
    hl.exec_cmd("qs -c overview")
    hl.exec_cmd("bash ~/.config/hypr/scripts/post_start.sh")
    hl.exec_cmd(
        "systemd-inhibit --who='Hyprland config' --why='Hyprlock keybind' --what=handle-power-key --mode=block sleep infinity & echo $! > /tmp/.hyprland-systemd-inhibit")
end)

hl.on("hyprland.shutdown", function()
    hl.exec_cmd('kill -9 "$(cat /tmp/.hyprland-systemd-inhibit)')
end)
